test:
  adapter: <%= ENV.fetch('DATABASE_ADAPTER', 'sqlite3') %>
  <% if ENV['DATABASE_ADAPTER'] == 'postgresql' %>
  database: searchable_records_test
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>
  pool: 5
  timeout: 5000
  <% elsif ENV['DATABASE_ADAPTER'] == 'mysql2' %>
  database: searchable_records_test
  username: <%= ENV.fetch('MYSQL_USER', 'root') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', 'mysql') %>
  host: <%= ENV.fetch('MYSQL_HOST', 'localhost') %>
  port: <%= ENV.fetch('MYSQL_PORT', 3306) %>
  pool: 5
  timeout: 5000
  <% else %>
  database: ":memory:"
  <% end %>